In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score

In [2]:
data = pd.read_csv(r"C:\Users\farha\Downloads\dataset.csv")

In [3]:
data.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [4]:
data.tail()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
11050                -1                         1              1   
11051                -1                        -1             -1   
11052                 1                         1             -1   
11053                 1                         1             -1   
11054                 1                         1             -1   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
11050                  1               1                           -1  ...   
11051                  1              -1                           -1  ...   
11052                  1              -1                           -1  ...   
11053                 -1              -1                            1  ...   
11054                 -1              -1                            1  ...   

       popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
11050           -1      -1              1          1           -1         -1   
11051           -1       1              1          1            1          1   
11052            1       1              1          1            1         -1   
11053           -1       1              1          1            1         -1   
11054            1       1             -1          1           -1         -1   

       Google_Index  Links_pointing_to_page  Statistical_report  Result  
11050             1                       1                   1       1  
11051             1                      -1                   1      -1  
11052             1                       0                   1      -1  
11053             1                       1                   1      -1  
11054            -1                       1                  -1      -1  

[5 rows x 32 columns]

In [5]:
data.info()
data.isnull().any()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

## Splitting Data into X and Y

In [6]:
x=data.iloc[:,1:31].values
y=data.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

## Model Building

## Regression

In [8]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [9]:
y_pred_lr = lr.predict(x_test)
test_acc_lr = accuracy_score(y_test,y_pred_lr)*100
print("Accuracy on test Data: ",test_acc_lr)

Accuracy on test Data:  91.67797376752601


## Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier
ranf= RandomForestClassifier()
ranf.fit(x_train,y_train)

RandomForestClassifier()

In [100]:
y_pred_ranf = ranf.predict(x_test)
y_train_rf = ranf.predict(x_train)
test_acc_ranf = accuracy_score(y_test,y_pred_ranf)*100
acc_train_rf = accuracy_score(y_train,y_train_rf)*100
print("Accuracy on training Data: ",acc_train_rf)
print("Accuracy on test Data: ",test_acc_ranf)

Accuracy on training Data:  99.02758932609679
Accuracy on test Data:  97.01492537313433


In [12]:
confusion_matrix(y_pred_ranf, y_test)

array([[ 961,   16],
       [  53, 1181]], dtype=int64)

In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_ranf))

              precision    recall  f1-score   support

          -1       0.98      0.95      0.97      1014
           1       0.96      0.99      0.97      1197

    accuracy                           0.97      2211
   macro avg       0.97      0.97      0.97      2211
weighted avg       0.97      0.97      0.97      2211



## Hyperparameter (GridSearch CV)

In [79]:
# Number of trees in random forest
n_estimators =  [100, 150, 200]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [20,30,40]
# Minimum number of samples required to split a node
min_samples_split = [2, 5]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2]
# Method of selecting samples for training each tree
bootstrap = [True, False]

param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(param_grid)

{'n_estimators': [100, 150, 200], 'max_features': ['auto', 'sqrt'], 'max_depth': [20, 30, 40], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2], 'bootstrap': [True, False]}


In [80]:
hp_rf_model = RandomForestClassifier()
hp_rf_model

RandomForestClassifier()

In [81]:
from sklearn.model_selection import GridSearchCV
rf_Grid = GridSearchCV(estimator = hp_rf_model, param_grid = param_grid, cv = 3, verbose=2, n_jobs = -1)

In [82]:
rf_Grid.fit(x_train, y_train)

Fitting 3 folds for each of 144 candidates, totalling 432 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False], 'max_depth': [20, 30, 40],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 150, 200]},
             verbose=2)

In [83]:
rf_Grid.best_params_

{'bootstrap': False,
 'max_depth': 30,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 150}

In [98]:
print (f'Train Accuracy - : {rf_Grid.score(x_train,y_train):.3f}')
print (f'Test Accuracy - : {rf_Grid.score(x_test,y_test):.3f}')

Train Accuracy - : 0.990
Test Accuracy - : 0.969


## SVM

In [13]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(x_train, y_train)

SVC()

In [14]:
y_pred_svm = svm.predict(x_test)
test_acc_svm = accuracy_score(y_test,y_pred_svm)*100
print("Accuracy on test Data: ",test_acc_svm)

Accuracy on test Data:  94.07507914970601


In [15]:
confusion_matrix(y_pred_svm, y_test)

array([[ 933,   50],
       [  81, 1147]], dtype=int64)

## Pickle

In [16]:
import pickle
pickle.dump(ranf,open('Phishing_Website.pkl','wb'))